id: P009273
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:03.459969
source_metadata:
  id: bdr:W3CN530
  title: རྡོ་རྗེ་སྙིང་པོའི་ཁྲིད་ཀྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    ecda3751807942c7be27d864242275be:
      image_group_id: I3CN8635
      title: ''
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
