id: P009273
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN530
  title: རྡོ་རྗེ་སྙིང་པོའི་ཁྲིད་ཀྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    ecda3751807942c7be27d864242275be:
      image_group_id: I3CN8635
      title: ''
      volume_number: 1
      total_pages: 104
